#!/bin/bash
#$ -pe mpich 4
#$ -N myjob
#$ -cwd
#$ -j y
#$ -S /bin/bash

export FILE_NAME="Laplasexe1"
export MPICH2_ROOT="/opt/mpich2/gnu"
export PATH="$MPICH2_ROOT/bin:$PATH"
$MPICH2_ROOT/bin/mpiexec -machinefile $TMPDIR/machines -n $NSLOTS ./$FILE_NAME
exit 0
